services:
    olx-watcher:
        build:
            context: ./.docker/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: olx-watcher-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - '.:/var/www/html'
        networks:
            - olx-watcher
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - olx-watcher
#        depends_on:
#            - redis
#    redis:
#        image: 'redis:alpine'
#        ports:
#            - '${FORWARD_REDIS_PORT:-6379}:6379'
#        volumes:
#            - 'olx-watcher-redis:/data'
#        networks:
#            - olx-watcher
#        healthcheck:
#            test:
#                - CMD
#                - redis-cli
#                - ping
#            retries: 3
#            timeout: 5s
networks:
    olx-watcher:
        driver: bridge
#volumes:
#    olx-watcher-redis:
#        driver: local
