version: '3'
services:
  olx-watcher:
    build:
      context: ./
      dockerfile: Dockerfile
    image: olx-watcher-8.3/app
    container_name: olx-watcher
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:8080'
    volumes:
      - '.:/var/www/html'
    networks:
      - olx-watcher
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'olx-watcher-redis:/data'
    networks:
      - olx-watcher
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  mail:
    image: boky/postfix
    environment:
      - ALLOWED_SENDER_DOMAINS=olx-watcher.com
      - POSTFIX_always_add_missing_headers=yes
      - HOSTNAME=olx-watcher.com
    networks:
      - olx-watcher
networks:
  olx-watcher:
    driver: bridge
volumes:
  olx-watcher-redis:
    driver: local
