version: '3'
services:
  olx-watcher:
    build:
      context: ./
      dockerfile: Dockerfile
    image: olx-watcher-8.3/app
    container_name: olx-watcher
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:8080'
    volumes:
      - '.:/var/www/html'
    networks:
      - olx-watcher
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - olx-watcher
networks:
  olx-watcher:
    driver: bridge
